FROM python:3
USER root
RUN apt-get update
RUN apt-get install -y vim less
RUN apt-get install -y zsh less
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
# streamlit
RUN pip install streamlit
RUN pip install pandas
RUN pip install scipy
RUN pip install streamlit
RUN pip install pymongo
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
EXPOSE 80
COPY . .
CMD streamlit run analytics.py